settings:
  title: 'Status Page'
  url: 'https://status.praise.ml' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 7 # number of days you want to display in histogram
  collectResponseTimes: false # experimental feature, enable only for <5 monitors or on paid plans

  # configurable texts across the status page
  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: 'Some checks failed'

# list of monitors
monitors:
  - id: mmc-praise-ml # unique identifier
    name: mmc.praise.ml
    description: 'Massive Media Center' # default=empty
    url: 'https://mmc.praise.ml/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
