settings:
  title: 'Status Page'
  url: 'https://status.praise.ml' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: false # experimental feature, enable only for <5 monitors or on paid plans

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: mmc
    name: Massive Media Center
    url: 'https://mmc.praise.ml'
    method: GET
    expectStatus: 200

  - id: rmc
    name: Restricted Media Center
    url: 'https://rmc.praise.ml/'
    method: GET
    expectStatus: 200
    
    - id: paste
    name: Paste Server
    url: 'https://paste.praise.ml/'
    method: GET
    expectStatus: 200
    
    - id: praise
    name: Praise Network Data Center
    url: 'https://praise.ml/'
    method: GET
    expectStatus: 200
